package com.pixelMind.materialGrid.controller;

import com.pixelMind.materialGrid.dto.request.PersonCreateRequest;
import com.pixelMind.materialGrid.dto.request.PersonUpdateRequest;
import com.pixelMind.materialGrid.dto.response.ApiResponse;
import com.pixelMind.materialGrid.dto.response.PageResponse;
import com.pixelMind.materialGrid.dto.response.PersonResponse;
import com.pixelMind.materialGrid.service.PersonService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Pageable;
import org.springframework.data.web.PageableDefault;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

@Tag(name = "Persons", description = "Person master-data management with server-generated person codes")
@RestController
@RequestMapping("/api/v1/persons")
@RequiredArgsConstructor
public class PersonController {

    private final PersonService personService;

    @Operation(summary = "Create a person. personCode is generated by the server.")
    @PostMapping
    public ResponseEntity<ApiResponse<PersonResponse>> create(@Valid @RequestBody PersonCreateRequest request) {
        return ResponseEntity.status(HttpStatus.CREATED)
                .body(ApiResponse.success("Person created successfully", personService.createPerson(request)));
    }

    @Operation(summary = "List persons (paginated, sortable, searchable by name)")
    @GetMapping
    public ResponseEntity<ApiResponse<PageResponse<PersonResponse>>> getAll(
            @RequestParam(required = false) String search,
            @PageableDefault(size = 20, sort = "id") Pageable pageable) {
        PageResponse<PersonResponse> page = new PageResponse<>(personService.getPersons(search, pageable));
        return ResponseEntity.ok(ApiResponse.success("Persons retrieved successfully", page));
    }

    @Operation(summary = "Get a person by id")
    @GetMapping("/{id}")
    public ResponseEntity<ApiResponse<PersonResponse>> getOne(@PathVariable Long id) {
        return ResponseEntity.ok(ApiResponse.success("Person retrieved successfully", personService.getPerson(id)));
    }

    @Operation(summary = "Update a person (personCode is immutable)")
    @PutMapping("/{id}")
    public ResponseEntity<ApiResponse<PersonResponse>> update(
            @PathVariable Long id, @Valid @RequestBody PersonUpdateRequest request) {
        return ResponseEntity.ok(ApiResponse.success("Person updated successfully", personService.updatePerson(id, request)));
    }

    @Operation(summary = "Delete a person")
    @DeleteMapping("/{id}")
    public ResponseEntity<ApiResponse<Void>> delete(@PathVariable Long id) {
        personService.deletePerson(id);
        return ResponseEntity.ok(ApiResponse.success("Person deleted successfully", null));
    }
}