spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://187.52.124.152:3307/material_grid_qa_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Colombo}
    username: ${DB_USERNAME:materialgrid_qa_admin}
    password: ${DB_PASSWORD:materialgridqaadmin}
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: Asia/Colombo

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080

app:
  security:
    session-token-header: Authorization
    session-token-prefix: "Bearer "
    session-idle-timeout-minutes: 30

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    com.example.materialGrid: INFO